version: "2"
linters:
  default: all
  disable:
    - mnd
    - testpackage
    - wsl
  enable:
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/mcpherrinm/rfc3161test
