version: "2"
linters:
  default: all
  disable:
    - cyclop
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - mnd
    - nestif
    - perfsprint
    - testpackage
    - varnamelen
    - wsl
  enable:
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/mcpherrinm/rfc3161test
            - golang.org/x/crypto
